# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: MON AMOUR EST ORIGINAIRE D’UKRAINE.
email: maruf.tuyel@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  
Liudmyla est originaire d’Ukraine. C’est ma femme. Je l’aime tellement. En octobre dernier, j’ai vraiment embrassé sur son chèque. En gros, elle me manque tellement ! Je désire l’épouser. Mais malheureusement, elle m’a fait pleurer. C’est pourquoi je me sens si brisé à propos d’elle. Même elle n’est pas vraiment aussi efficace en Ukraine. Elle quitta Ukrane. À l’heure actuelle, l’Ukraine est un pays d’effusion de sang. Je pense qu’elle a pris la ferme décision de ne pas retourner en Ukraine. C’est pour ça qu’elle est si gentille avec moi. Je me sens vraiment hypnotisée quand je me souviens d’elle.  
baseurl: "/tuyel" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MARUF TUYEL
_username:  maruftuyel.io 

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
